import { useEffect, useRef, useState, type ReactNode } from 'react'
import {
  Room,
  RoomEvent,
  Track,
  type Participant,
  type RemoteTrack,
  type TranscriptionSegment,
} from 'livekit-client'
import type { CallEvent } from '../types'
import { api, ApiError } from '../api'
import { describeRule, LevelChip } from './LevelChip'
import { EXAMPLES, GLOSSES } from '../examples'
import exampleCall from '../exampleCall.json'

/** Same topic call_events.py publishes on. */
const EVENTS_TOPIC = 'vo.events'

/** Generated by scripts/make_example_call.py from the real router. */
const EXAMPLE = exampleCall as CallEvent[]

type Status = 'idle' | 'connecting' | 'live' | 'ended' | 'error'
type TurnEvent = Extract<CallEvent, { type: 'turn' }>

const AGENT_STATES: Record<string, string> = {
  initializing: 'Agent is joining…',
  listening: 'Listening',
  thinking: 'Thinking',
  speaking: 'Speaking',
}

const stripSpeaker = (reply: string) => reply.replace(/^\[[^\]]*\]\s*/, '')

const formatTimer = (seconds: number) =>
  `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`

/** Why the router gave this turn to this agent, in one or two sentences. */
function explainTurn(ev: TurnEvent): ReactNode {
  const closed =
    ev.excluded.length > 0 ? (
      <>
        {ev.excluded.map((a, i) => (
          <span key={a.id}>
            {i > 0 && ', '}
            <s>{a.name}</s>
          </span>
        ))}{' '}
        closed: {ev.excluded.map((a) => describeRule(a.rule)).join('; ')}.{' '}
      </>
    ) : null
  let decision: ReactNode
  if (ev.resolved_by === 'pattern') {
    decision = ev.keyword ? (
      <>
        <mark>{ev.keyword}</mark> is a keyword of <strong>{ev.agent_name}</strong>.
      </>
    ) : (
      <>
        A keyword points to <strong>{ev.agent_name}</strong>.
      </>
    )
  } else if (ev.resolved_by === 'gate_only') {
    decision =
      ev.eligible.length === 0 ? (
        <>
          <strong>{ev.from_agent_name}</strong> has no specialists below it, so it keeps the call.
        </>
      ) : (
        <>
          Only <strong>{ev.agent_name}</strong> is open to this caller.
        </>
      )
  } else {
    decision = (
      <>
        No single keyword match, so the model{' '}
        {ev.handed_off ? (
          <>
            handed the call to <strong>{ev.agent_name}</strong>.
          </>
        ) : (
          <>
            kept the call with <strong>{ev.agent_name}</strong>.
          </>
        )}
        {ev.simulated && (
          <span className="call-route__note"> Simulated: no language model on this server, so the reply is a placeholder.</span>
        )}
      </>
    )
  }
  return (
    <>
      {closed}
      {decision}
    </>
  )
}

function Timeline({
  events,
  callerLabel,
  pending,
  endedByYou,
  glossed,
}: {
  events: CallEvent[]
  callerLabel: string
  pending: string | null
  endedByYou: boolean
  glossed: boolean
}) {
  const items: ReactNode[] = []
  events.forEach((ev, i) => {
    if (ev.type === 'greeting') {
      items.push(
        <li key={`g${i}`} className="call-msg call-msg--agent">
          <span className="call-msg__who">{ev.agent_name}</span>
          <p lang="it">{ev.text}</p>
        </li>,
      )
    } else if (ev.type === 'turn') {
      items.push(
        <li key={`c${ev.seq}`} className="call-msg call-msg--caller">
          <span className="call-msg__who">{callerLabel}</span>
          <p lang="it">{ev.caller}</p>
          {glossed && GLOSSES[ev.caller] && <span className="call-msg__gloss">{GLOSSES[ev.caller]}</span>}
        </li>,
        <li key={`r${ev.seq}`} className={`call-route call-route--${ev.resolved_by}`}>
          <LevelChip level={ev.resolved_by} />
          <span className="call-route__text">{explainTurn(ev)}</span>
          {ev.latency_ms != null && <span className="call-route__ms">{ev.latency_ms.toFixed(1)} ms</span>}
        </li>,
      )
      if (ev.handed_off) {
        items.push(
          <li key={`h${ev.seq}`} className="call-mark">
            Handed over: {ev.from_agent_name} → <strong>{ev.agent_name}</strong>
          </li>,
        )
      }
      items.push(
        <li key={`a${ev.seq}`} className="call-msg call-msg--agent">
          <span className="call-msg__who">
            {ev.agent_name}
            {ev.tools.map((t) => (
              <code key={t} className="call-tool">
                {t}
              </code>
            ))}
          </span>
          <p lang="it">{stripSpeaker(ev.reply)}</p>
        </li>,
      )
    } else {
      items.push(
        <li key={`e${i}`} className="call-mark call-mark--end">
          {ev.reason === 'end_call' ? 'The agent ended the call (end_call tool)' : 'Call ended'}
        </li>,
      )
    }
  })
  if (pending) {
    items.push(
      <li key="pending" className="call-msg call-msg--caller call-msg--pending">
        <span className="call-msg__who">{callerLabel}</span>
        <p lang="it">{pending}</p>
      </li>,
    )
  }
  if (endedByYou && !events.some((e) => e.type === 'ended')) {
    items.push(
      <li key="hangup" className="call-mark call-mark--end">
        You hung up
      </li>,
    )
  }
  return <ol className="call-timeline">{items}</ol>
}

/** The call page. Joins a LiveKit room with the browser's microphone and
 * plays the agent's audio, like any LiveKit client. What makes it more than
 * a phone: the voice worker publishes one event per turn on the room's data
 * channel (topic `vo.events`, see call_events.py), and the timeline is built
 * from those, so each answer comes with the router level that picked the
 * agent, the agents the gate closed, the keyword, handovers and tools.
 * Before the first call the timeline shows an example call, labeled as one. */
export function VoiceTestConsole() {
  const [configured, setConfigured] = useState<boolean | null>(null)
  const [status, setStatus] = useState<Status>('idle')
  const [error, setError] = useState<string | null>(null)
  const [events, setEvents] = useState<CallEvent[] | null>(null)
  const [pending, setPending] = useState<string | null>(null)
  const [agentState, setAgentState] = useState<string | null>(null)
  const [startedAt, setStartedAt] = useState<number | null>(null)
  const [elapsed, setElapsed] = useState(0)
  const [endedByYou, setEndedByYou] = useState(false)
  const roomRef = useRef<Room | null>(null)
  const audioRef = useRef<HTMLAudioElement | null>(null)
  const timelineRef = useRef<HTMLDivElement | null>(null)

  useEffect(() => {
    api
      .getVoiceStatus()
      .then((s) => setConfigured(s.configured))
      .catch(() => setConfigured(false))
    return () => {
      roomRef.current?.disconnect()
    }
  }, [])

  useEffect(() => {
    if (status !== 'live' || startedAt === null) return
    const id = window.setInterval(() => setElapsed((Date.now() - startedAt) / 1000), 500)
    return () => window.clearInterval(id)
  }, [status, startedAt])

  useEffect(() => {
    const el = timelineRef.current
    if (el && events) el.scrollTop = el.scrollHeight
  }, [events, pending])

  const connect = async () => {
    setError(null)
    setStatus('connecting')
    setEvents([])
    setPending(null)
    setAgentState(null)
    setEndedByYou(false)
    setElapsed(0)
    try {
      const { token, url } = await api.getVoiceToken()
      const room = new Room()
      roomRef.current = room

      room.on(RoomEvent.TrackSubscribed, (track: RemoteTrack) => {
        if (track.kind === Track.Kind.Audio && audioRef.current) track.attach(audioRef.current)
      })

      room.on(RoomEvent.DataReceived, (payload: Uint8Array, _p?: Participant, _k?: unknown, topic?: string) => {
        if (topic !== EVENTS_TOPIC) return
        try {
          const ev = JSON.parse(new TextDecoder().decode(payload)) as CallEvent
          setEvents((prev) => [...(prev ?? []), ev])
          if (ev.type === 'turn') setPending(null)
        } catch {
          // not one of ours
        }
      })

      // The caller's words while they speak; the turn event replaces them.
      room.on(RoomEvent.TranscriptionReceived, (segments: TranscriptionSegment[], participant?: Participant) => {
        if (!participant || participant.identity !== room.localParticipant.identity) return
        const text = segments.map((s) => s.text).join(' ').trim()
        if (text) setPending(text)
      })

      room.on(RoomEvent.ParticipantAttributesChanged, (changed: Record<string, string>, participant: Participant) => {
        if (participant.isLocal) return
        const state = changed['lk.agent.state']
        if (state) setAgentState(state)
      })

      room.on(RoomEvent.Disconnected, () => {
        roomRef.current = null
        setStatus('ended')
        setAgentState(null)
      })

      await room.connect(url, token)
      await room.localParticipant.setMicrophoneEnabled(true)
      for (const p of room.remoteParticipants.values()) {
        const state = p.attributes['lk.agent.state']
        if (state) setAgentState(state)
      }
      setStartedAt(Date.now())
      setStatus('live')
    } catch (err) {
      setError(err instanceof ApiError ? err.message : String(err))
      setStatus('error')
      setEvents(null)
      roomRef.current?.disconnect()
      roomRef.current = null
    }
  }

  const hangUp = () => {
    setEndedByYou(true)
    roomRef.current?.disconnect()
  }

  const showing = events ?? EXAMPLE
  const isExample = events === null
  const lastAgent = [...showing].reverse().find((e) => e.type !== 'ended') as Exclude<CallEvent, { type: 'ended' }> | undefined

  const statusLabel =
    status === 'live'
      ? AGENT_STATES[agentState ?? 'initializing'] ?? 'On a call'
      : status === 'connecting'
        ? 'Connecting…'
        : status === 'ended'
          ? 'Call ended'
          : configured === false
            ? 'Calls are off on this server'
            : 'Ready'

  return (
    <div className="call">
      <aside className="call-panel">
        <div className={`call-status call-status--${status} call-status--${agentState ?? 'none'}`}>
          <span className="call-status__dot" aria-hidden />
          <span className="call-status__label" role="status">
            {statusLabel}
          </span>
          {(status === 'live' || status === 'ended') && <span className="call-status__timer">{formatTimer(elapsed)}</span>}
        </div>

        {status === 'live' && lastAgent && (
          <p className="call-panel__agent">
            On the line: <strong>{lastAgent.agent_name}</strong>
          </p>
        )}

        {status === 'live' ? (
          <button type="button" className="btn-danger call-panel__btn" onClick={hangUp}>
            End call
          </button>
        ) : (
          <button
            type="button"
            className="btn-primary call-panel__btn"
            onClick={connect}
            disabled={configured !== true || status === 'connecting'}
          >
            {status === 'connecting' ? 'Connecting…' : status === 'ended' ? 'Call again' : 'Start a call'}
          </button>
        )}

        {configured === false && (
          <p className="call-panel__off">
            This server has no LiveKit credentials, so live calls are off. The example call shows what a
            call looks like.
          </p>
        )}
        {error && <p className="error">{error}</p>}

        <div className="call-panel__tips">
          <h2>Try saying</h2>
          <ul>
            {EXAMPLES.map((ex) => (
              <li key={ex.text}>
                <span lang="it">{ex.text}</span>
                <span className="call-panel__gloss">{ex.gloss}</span>
              </li>
            ))}
            <li>
              <span lang="it">Arrivederci</span>
              <span className="call-panel__gloss">goodbye: the agent hangs up</span>
            </li>
          </ul>
          <p className="call-panel__fine">
            Uses your microphone. The agents speak Italian. Calls are recorded in Calls, marked as voice.
          </p>
        </div>
      </aside>

      <section className="call-main" aria-label={isExample ? 'Example call' : 'This call'}>
        <header className="call-main__head">
          {isExample ? (
            <>
              <span className="call-badge">Example call</span>
              <p>
                A scripted caller run through the real router, with the demo's placeholder replies. Start a call and
                yours replaces it, turn by turn.
              </p>
            </>
          ) : (
            <>
              <span className="call-badge call-badge--live">{status === 'live' ? 'Live' : 'Your call'}</span>
              <p>Each turn shows which router level picked the agent, and why.</p>
            </>
          )}
        </header>
        <div className={isExample ? 'call-main__body' : 'call-main__body call-main__body--live'} ref={timelineRef}>
          {!isExample && showing.length === 0 && !pending ? (
            <p className="call-main__empty">
              {status === 'connecting' ? 'Connecting to the room…' : 'Waiting for the receptionist to pick up…'}
            </p>
          ) : (
            <Timeline
              events={showing}
              callerLabel={isExample ? 'Caller' : 'You'}
              pending={pending}
              endedByYou={endedByYou}
              glossed={isExample}
            />
          )}
        </div>
      </section>

      {/* eslint-disable-next-line jsx-a11y/media-has-caption */}
      <audio ref={audioRef} autoPlay />
    </div>
  )
}
